# DEV
version: "3"

services:
  database-neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${NEO4J_BASE_DIR}/conf:/conf
      - ${NEO4J_BASE_DIR}/data:/data
      - ${NEO4J_BASE_DIR}/import:/import
      - ${NEO4J_BASE_DIR}/logs:/logs
      - ${NEO4J_BASE_DIR}/plugins:/plugins
    env_file:
      - .env
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
